apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded 'admin'
  password: cGFzc3dvcmQ=  # base64 encoded 'password'
  repl_username: cmVwbGljYQ==  # base64 encoded 'replica'
  repl_password: cmVwbGljcGFzcw==  # base64 encoded 'replpass'
