apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
    role: slave
